---
namespace: tolecnal
name: pihole_doh
version: "2.0.0"
readme: README.md

authors:
  - "Jostein Elvaker Haande <tolecnal@tolecnal.net>"
description: Deploy pihole with DNSCrypt proxy for encrypted DNS
license:
  - MIT

tags:
  - dns
  - pihole
  - dnscrypt
  - tools
  - linux

repository: https://github.com/tolecnal/tolecnal.pihole_doh
documentation: https://github.com/tolecnal/tolecnal.pihole_doh
homepage: https://tolecnal.net
issues: https://github.com/tolecnal/tolecnal.pihole_doh/issues

build_ignore: []
