---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  vars:
    web_pass: "molecule_test_password"
    docker_pihole_custom_lists:
      - "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"
      - "https://v.firebog.net/hosts/AdguardDNS.txt"

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      changed_when: false
      when: ansible_facts['os_family'] == 'Debian'

  roles:
    - role: tolecnal.pihole_doh
