---
role_name_check: 1
dependency:
  name: galaxy
  options:
    roles-path: "${MOLECULE_SCENARIO_DIRECTORY}/roles"
    role-file: ${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml
driver:
  name: docker
platforms:
  - name: ubuntu-2404
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2404}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: debian13
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian13}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_SCENARIO_DIRECTORY}/roles:${MOLECULE_PROJECT_DIRECTORY}/.."
  playbooks:
    prepare: prepare.yml
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
