---
- name: Prepare
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Create Docker config directory
      ansible.builtin.file:
        path: /etc/docker
        state: directory
        mode: "0755"

    - name: Configure Docker daemon to use vfs storage driver
      ansible.builtin.copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "storage-driver": "vfs"
          }
        mode: "0644"
