---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:

    - name: Verify .zshrc exists
      ansible.builtin.stat:
        path: ~/.zshrc
      register: conf_result

    - name: The zsh configuration file exists
      ansible.builtin.debug:
        msg: "The zsh configuration file exists"
      when: conf_result.stat.exists

    - name: Verify that p10k config file exists
      ansible.builtin.stat:
        path: ~/.p10k.zsh
      register: tpm_result

    - name: The p10k config file is installed
      ansible.builtin.debug:
        msg: "The p10k config file is installed"
      when: tpm_result.stat.exists
